language: ruby
script: 'bundle exec rake spec'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: rbx-18mode  
    - rvm: 1.8.7
notifications:
  email:
    - mbj@seonic.net
